# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  name: 'SimpleAPI'
  inputs:
    command: 'publish'
    publishWebProjects: true
    modifyOutputPath: true
    arguments: '--configuration $(buildConfiguration) -o $(Pipeline.Workspace)/publish/SimpleAPI'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/publish/SimpleAPI'
    artifact: 'SimpleAPI'
    publishLocation: 'pipeline'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Petteri - MSDN (f70471bf-4538-41e6-a84c-679ec53940ef)'
    appType: 'webApp'
    WebAppName: 'ubi-simple-api'
    packageForLinux: '$(Pipeline.Workspace)/publish/SimpleAPI/**/*.zip'
