# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: SimpleAPI
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'publish'
    publishWebProjects: false
    modifyOutputPath: false
    arguments: '$(project) --configuration $(buildConfiguration) -o $(Pipeline.Workspace)/publish/$(project)'
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure DevOps'
    appType: 'webApp'
    WebAppName: 'ubi-simple-api'
    packageForLinux: '$(Pipeline.Workspace)/publish/$(project)/**/*.zip'